#ifndef FAKE_XPARAMETERS_H 
#define FAKE_XPARAMETERS_H  

/* placeholder */

#define XPAR_BONDMACHINEIP1_0_S00_AXI_BASEADDR 0x00000000
#define BONDMACHINEIP1_S00_AXI_SLV_REG1_OFFSET 0
#define BONDMACHINEIP1_S00_AXI_SLV_REG0_OFFSET 0

#define LED_BASE XPAR_BONDMACHINEIP1_0_S00_AXI_BASEADDR

#endif
